# Generated by Django 3.2.12 on 2022-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
