# Generated by Django 3.2.12 on 2022-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_postlike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='btc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='eth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='eur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='gbp',
            field=models.FloatField(),
        ),
    ]
