# Generated by Django 4.0.2 on 2022-02-13 09:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='...'),
            preserve_default=False,
        ),
    ]
