# Generated by Django 4.0.2 on 2022-02-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='porfile_picture',
            new_name='profile_picture',
        ),
    ]
